GET http://127.0.0.1:8765/wiki

###

PUT http://127.0.0.1:8765/lab/book/set HTTP/1.1
Content-Type: application/x-www-form-urlencoded

book_name=运营之光：我的互联网运营方法论与自白&book_isbn=9787121298097&book_url=http://product.dangdang.com/24029311.html&book_price=28.9

###

POST http://127.0.0.1:8765/dawn/book/create HTTP/1.1
Content-Type: application/json

{
    "user": "wangyu",
    "plan": "123",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

DELETE http://127.0.0.1:8765/mica/task/edit/id/23

###

GET http://127.0.0.1:8765/team/worker/

###

GET http://127.0.0.1:8765/road