GET http://127.0.0.1:8765/wiki

###

PUT http://127.0.0.1:8765/mica/plan/info/type/ugc/mark/10 HTTP/1.1
Content-Type: application/x-www-form-urlencoded

user=wangyu&plan=123

###

POST http://127.0.0.1:8765/dawn/book/create HTTP/1.1
Content-Type: application/json

{
    "user": "wangyu",
    "plan": "123",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

DELETE http://127.0.0.1:8765/mica/task/edit/id/23

###

GET http://127.0.0.1:8765/team/worker/

###

GET http://127.0.0.1:8765/road