GET http://127.0.0.1:8765/hello

###

POST http://127.0.0.1:8765 HTTP/1.1
Content-Type: application/x-www-form-urlencoded;charset=utf-8

user=wangyu
plan=123

###

POST http://127.0.0.1:8765 HTTP/1.1
Content-Type: application/json

{
    "user": "wangyu",
    "plan": "123",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}